tags: str1, str2
test_data: local

browser: chrome # chrome or firefox

remote:  # for remote test, must cantain a client. if windows, can use a bat command for start the jar "cd /d %~dp0, start java -jar selenium-server-standalone-2.33.0.jar"
  remote_enable: 0  # 0 or 1
  remote_address: 192.168.3.52

profile: 
  firefox: seo # fill your firefox profile or keep it null. only valid for firefox
  chrome: 

proxy:
  proxy_enable: 1 # 0 or 1
  proxy_host: 127.0.0.1
  proxy_port: 12001
  proxy_no_proxies_on: '127.0.0.1, localhost, .baidu.com, .cent.com'

host:
  http: http://www.test.com/
  https: https://www.test.com/
  my: http://my.test.com/
  help: http://help.test.com/

version: v20131028 # fill the version which needs to be tested, otherwise keep it null.